CREATE TABLE MEMBERS (
    IDX NUMBER(10) PRIMARY KEY,
    NAME VARCHAR2(30),
    AGE NUMBER(3),
    ADDR VARCHAR2(150),
    REGDATE DATE DEFAULT SYSDATE
);
CREATE SEQUENCE MEMBERS_SEQ NOCACHE; --시퀀스 생성

INSERT INTO MEMBERS
VALUES (MEMBERS_SEQ.NEXTVAL, '홍길동1', 27, '서울', SYSDATE);
INSERT INTO MEMBERS
VALUES (MEMBERS_SEQ.NEXTVAL, '홍길동2', 30, '대전', SYSDATE);
INSERT INTO MEMBERS
VALUES (MEMBERS_SEQ.NEXTVAL, '김유신', 40, '대구', SYSDATE);
INSERT INTO MEMBERS
VALUES (MEMBERS_SEQ.NEXTVAL, '이순신', 38, '부산', SYSDATE);
COMMIT;

SELECT * FROM MEMBERS;

SELECT * FROM MEMBERS ORDER BY NAME
;

--이름으로 검색
SELECT * FROM MEMBERS
WHERE NAME LIKE '%' || :NAME || '%' --검색조건 데이터 필요(파라미터)
ORDER BY NAME
;

SELECT *
FROM MEMBERS
WHERE NAME LIKE '%' || '길동'|| '%'
;'
