CREATE TABLE STUDENT (
    ID VARCHAR2(10) PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    KOR NUMBER(3) DEFAULT 0 CHECK (KOR BETWEEN 0 AND 100),
    ENG NUMBER(3) DEFAULT 0 CHECK (ENG BETWEEN 0 AND 100),
    MATH NUMBER(3) DEFAULT 0 CHECK (MATH BETWEEN 0 AND 100),
    TOTAL NUMBER(3) DEFAULT 0 CHECK (TOTAL BETWEEN 0 AND 100),
    AVG NUMBER(5,2) DEFAULT 0 CHECK (AVG BETWEEN 0 AND 100)
);
INSERT INTO STUDENT (ID, NAME, KOR, ENG, MATH, TOTAL, AVG)
VALUES ('2023001', '홍길동', 100, 90, 81, 0, 0);
INSERT INTO STUDENT (ID, NAME, KOR, ENG, MATH)
VALUES ('2023002', '홍길동2', 90, 80, 75);

SELECT * FROM STUDENT;
COMMIT;

ALTER TABLE STUDENT
DROP COLUMN TOTAL;

alter TABLE STUDENT
    tot BETWEEN 0 AND 300
    ;
    
CREATE TABLE STUDENT (
TOTAL NUMBER(3) DEFAULT 0,
CONSTRAINT CHK_TOTAL_RANGE CHECK (TOT BETWEEN 0 AND 300)
);

ALTER TABLE STUDENT
ADD CONSTRAINT TOT CHECK (TOT BETWEEN 0 AND 300);

ALTER TABLE STUDENT
MODIFY AVG NUMBER(3) AFTER TOT;
commit;

