/* UNION, UNION ALL : 합집합 처리
- UNION : 중복데이터는 하나만 선택
- UNION ALL : 모든 데이터를 선택(중복데이터도)
(주의) 조회하는 컬럼의 이름, 순서, 개수, 타입이 일치하도록 작성한다.
*******************/
-- UNION 사용 예제
SELECT CUSTID, NAME FROM CUSTOMER WHERE CUSTID IN (1,2,3);
SELECT CUSTID, NAME FROM CUSTOMER WHERE CUSTID IN (3,4,5);

-- UNION으로 합하기 : 중복데이터는 1개만 선택
SELECT CUSTID, NAME FROM CUSTOMER WHERE CUSTID IN (1,2,3)
UNION
SELECT CUSTID, NAME FROM CUSTOMER WHERE CUSTID IN (3,4,5);

-- UNION ALL으로 합하기 : 중복데이터(동일데이터) 모두 선택
---- ORDER BY절은 마지막에만 사용 가능하다.
SELECT CUSTID, NAME FROM CUSTOMER WHERE CUSTID IN (1,2,3)
UNION ALL
SELECT CUSTID, NAME FROM CUSTOMER WHERE CUSTID IN (3,4,5)
ORDER BY NAME -- ORDER BY절은 마지막에만 한번 사용 가능
;
----------------
-- MINUS : 차집합(빼기)
SELECT CUSTID, NAME FROM CUSTOMER WHERE CUSTID IN (1,2,3)
MINUS
SELECT CUSTID, NAME FROM CUSTOMER WHERE CUSTID IN (3,4,5)
;
----------------
-- INTERSECT : 교집합(조인문 중 INNER JOIN에 해당)
SELECT CUSTID, NAME FROM CUSTOMER WHERE CUSTID IN (1,2,3)
INTERSECT
SELECT CUSTID, NAME FROM CUSTOMER WHERE CUSTID IN (3,4,5)
;
-- 조인문
SELECT *
  FROM (SELECT CUSTID, NAME FROM CUSTOMER WHERE CUSTID IN (1,2,3)) A,
       (SELECT CUSTID, NAME FROM CUSTOMER WHERE CUSTID IN (3,4,5)) B   
 WHERE A.CUSTID = B.CUSTID
   AND A.NAME = B.NAME
;  
----------------
-- 타입 일치해야한다.
/*SELECT CUSTID, NAME, 99 FROM CUSTOMER WHERE CUSTID IN (1,2,3)
UNION
SELECT CUSTID, NAME, '홍길동' FROM CUSTOMER WHERE CUSTID IN (3,4,5);
ORA-01790: expression must have same datatype as corresponding expression
*/





